# Generated by Django 4.0.1 on 2022-01-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
